### ISSUE TITLE
embeddings tensor type error

### ISSUE THREAD

**Issue by abdallah1097** [dayyass/pytorch_ner#40]
This error shows when running:
`$python main.py`

The error message is:
`RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.IntTensor instead (while checking arguments for embedding)`

Full error message:
```
$ python main.py
14it [00:00, ?it/s]
14it [00:00, ?it/s]
14it [00:00, ?it/s]
  0%|          | 0/1 [00:01<?, ?it/s]
epoch [1/10]

Traceback (most recent call last):
  File "main.py", line 230, in <module>
    main(path_to_config=args.config)
  File "main.py", line 195, in main
    train(
  File "D:\Work\GitHub Contributions\pytorch_ner\pytorch_ner\train.py", line 159, in train
    train_metrics = train_loop(
  File "D:\Work\GitHub Contributions\pytorch_ner\pytorch_ner\train.py", line 60, in train_loop
    logits = model(tokens, lengths)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Work\GitHub Contributions\pytorch_ner\pytorch_ner\nn_modules\architecture.py", line 23, in forward
    embed = self.embedding(x)  # EMBEDDINGS
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Work\GitHub Contributions\pytorch_ner\pytorch_ner\nn_modules\embedding.py", line 142, in forward
    return self.embedding(x)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\sparse.py", line 124, in forward
    return F.embedding(
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1852, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.IntTensor instead (while checking arguments for embedding)```

**Comment by dayyass** [comment]
@abdallah1097, which branch did you run?

**Comment by abdallah1097** [comment]
> @abdallah1097, which branch did you run?

Origin/Master, I can fix it by casting tensors (As I did to test my other pull requests) if this is a problem for others as well because I think it's related to my laptop since I got no GPU

**Comment by dayyass** [comment]
> > @abdallah1097, which branch did you run?
> 
> Origin/Master, I can fix it by casting tensors (As I did to test my other pull requests) if this is a problem for others as well because I think it's related to my laptop since I got no GPU

I will init LongTensor in NERCollator, but it is interesting, why this problem occurs, because I also use laptop without GPU and everything works correct

**Comment by dayyass** [comment]
> > @abdallah1097, which branch did you run?
> 
> Origin/Master, I can fix it by casting tensors (As I did to test my other pull requests) if this is a problem for others as well because I think it's related to my laptop since I got no GPU

Can you tell, which operating system you are using, python version and pytorch version (did you install pytorch from requirements.txt)?

**Comment by dayyass** [comment]
I added dtype=torch.long in collator - it should solve the problem
